import Navbar from "@/components/Navbar";
import {
  Fira_Sans,
  Noto_Sans,
  Rhodium_Libre,
  Roboto_Mono,
  Roboto_Serif,
} from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "./context/UserContext";

const inter = Fira_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <Navbar />
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
